version: '3'

services:
  webserver:
    image: fnagel/docker-typo3-webserver:${DOCKER_PHP_TAG}
    build:
      context: ./base
      args:
        php_tag: ${DOCKER_PHP_TAG}
        docker_image: "php"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - project:/var/www/project
    networks:
      - db
    depends_on:
      - db
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT}
      - APACHE_DOMAIN=${APACHE_DOMAIN}
      - APACHE_DOCUMENT_ROOT=/var/www/html/web

  db:
    image: mariadb:10.4
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - path=/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

# We use a single volume to make it easier to use docker hosting services
volumes:
  project:

networks:
  db:
