version: '3'

services:
  webserver:
    image: typo3.webserver.dev.${APACHE_DOMAIN}
    build: ./dev
    domainname: dev.${APACHE_DOMAIN}
    environment:
      - TYPO3_CONTEXT=Development
    networks:
      - mailhog

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mailhog

networks:
  mailhog:
