version: '3'

services:
  webserver:
    image: typo3.webserver.demo.${APACHE_DOMAIN}
    build:
      context: ./demo
    domainname: demo.${APACHE_DOMAIN}
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT}
      - APACHE_DOMAIN=demo.${APACHE_DOMAIN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TYPO3_USER=${TYPO3_USER}
      - TYPO3_PASSWORD=${TYPO3_PASSWORD}
