version: '3'

services:
  webserver:
    image: typo3.webserver.${APACHE_DOMAIN}
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    build:
      context: ../
      dockerfile: ./.docker/project/Dockerfile
    domainname: ${APACHE_DOMAIN}
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT}
      - APACHE_DOMAIN=${APACHE_DOMAIN}

  db:
    container_name: '${COMPOSE_PROJECT_NAME}-db'
